package client

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ai-router/image-generation-multilang/go/internal/config"
)

func TestGenerateAndEdit(t *testing.T) {
	imageBytes := []byte("fake-png-bytes")
	encoded := base64.StdEncoding.EncodeToString(imageBytes)
	var generationSeen, editSeen bool
	var generatedPath string

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("Authorization") != "Bearer test-key" {
			t.Errorf("authorization header = %q", r.Header.Get("Authorization"))
		}
		switch r.URL.Path {
		case "/v1/images/generations":
			generationSeen = true
			var body map[string]string
			if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
				t.Errorf("decode generation body: %v", err)
			}
			if body["model"] != "gpt-image-2" || body["response_format"] != "b64_json" {
				t.Errorf("unexpected generation body: %#v", body)
			}
			w.Header().Set("Content-Type", "application/json")
			fmt.Fprintf(w, `{"data":[{"b64_json":%q}]}`, encoded)
		case "/v1/images/edits":
			editSeen = true
			if err := r.ParseMultipartForm(1 << 20); err != nil {
				t.Errorf("parse multipart: %v", err)
				return
			}
			if r.FormValue("model") != "gpt-image-2" || r.FormValue("response_format") != "b64_json" {
				t.Errorf("unexpected edit fields: %#v", r.MultipartForm.Value)
			}
			file, _, err := r.FormFile("image")
			if err != nil {
				t.Errorf("image form field: %v", err)
				return
			}
			defer file.Close()
			got, _ := io.ReadAll(file)
			if string(got) != string(imageBytes) {
				t.Errorf("image bytes = %q", got)
			}
			w.Header().Set("Content-Type", "application/json")
			fmt.Fprintf(w, `{"data":[{"b64_json":%q}]}`, encoded)
		default:
			http.NotFound(w, r)
		}
	}))
	defer server.Close()

	cfg := config.Config{APIKey: "test-key", BaseURL: server.URL + "/v1", Model: "gpt-image-2", Size: "1024x1024", ResponseFormat: "b64_json"}
	api := New(cfg)
	got, err := api.Generate(context.Background(), "a studio portrait")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if string(got) != string(imageBytes) {
		t.Fatalf("generated bytes = %q", got)
	}

	dir := t.TempDir()
	generatedPath = filepath.Join(dir, "generated.png")
	if err := os.WriteFile(generatedPath, got, 0o600); err != nil {
		t.Fatal(err)
	}
	got, err = api.Edit(context.Background(), generatedPath, "add warm sunlight")
	if err != nil {
		t.Fatalf("Edit: %v", err)
	}
	if string(got) != string(imageBytes) {
		t.Fatalf("edited bytes = %q", got)
	}
	if !generationSeen || !editSeen {
		t.Fatalf("generationSeen=%v editSeen=%v", generationSeen, editSeen)
	}
}

func TestGenerateURLResponse(t *testing.T) {
	assetURL := ""
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/v1/images/generations":
			if r.Header.Get("Authorization") != "Bearer key" {
				t.Errorf("generation authorization header = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			fmt.Fprintf(w, `{"data":[{"url":%q}]}`, assetURL)
		case "/asset.png":
			if got := r.Header.Get("Authorization"); got != "" {
				t.Errorf("download leaked authorization header: %q", got)
			}
			w.Header().Set("Content-Type", "image/png")
			_, _ = w.Write([]byte("url-image"))
		}
	}))
	defer server.Close()
	assetURL = server.URL + "/asset.png"
	api := New(config.Config{APIKey: "key", BaseURL: server.URL + "/v1", ResponseFormat: "url"})
	got, err := api.Generate(context.Background(), "url test")
	if err != nil {
		t.Fatalf("Generate URL: %v", err)
	}
	if string(got) != "url-image" {
		t.Fatalf("downloaded bytes = %q", got)
	}
}

func TestDecodeBase64DataURL(t *testing.T) {
	want := []byte("hello")
	got, err := decodeBase64Image("data:image/png;base64," + base64.StdEncoding.EncodeToString(want))
	if err != nil || string(got) != string(want) {
		t.Fatalf("decode data URL: got %q, err %v", got, err)
	}
}

func TestEditRejectsMissingImage(t *testing.T) {
	api := New(config.Config{APIKey: "key", BaseURL: "http://localhost"})
	if _, err := api.Edit(context.Background(), "", "prompt"); err == nil || !strings.Contains(err.Error(), "image path") {
		t.Fatalf("expected image path validation, got %v", err)
	}
}

// Keep multipart imported in generated docs/examples and ensure the test file
// continues to compile if the standard library changes its aliases.
var _ multipart.File
